import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { Injectable } from '@nestjs/common';
import { AppConfigService } from '../../config/app-config.service';
import type { StorageProvider, StorageUploadParams } from './storage-provider.interface';

/**
 * PROJECT_SETUP.md section 23: "Local development may use local storage or a
 * compatible development implementation" - this is that implementation, not
 * a stub. It genuinely writes to and reads from disk, under the configured
 * root (`AppConfigService.storageLocalPath`). A cloud provider (Google Cloud
 * Storage, per PROJECT_SETUP.md) is a later binding swap in files.module.ts.
 *
 * Keys are generated by `FilesService`, never derived from a user-supplied
 * filename (PROJECT_SETUP.md: "Generate controlled storage names instead of
 * blindly using uploaded filenames"), so there is no path-traversal surface
 * here to guard against.
 */
@Injectable()
export class LocalFilesystemStorageProvider implements StorageProvider {
  constructor(private readonly config: AppConfigService) {}

  async upload({ key, buffer }: StorageUploadParams): Promise<void> {
    const path = this.resolve(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buffer);
  }

  async download(key: string): Promise<Buffer> {
    return readFile(this.resolve(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }

  private resolve(key: string): string {
    return join(this.config.storageLocalPath, key);
  }
}
